### ISSUE TITLE
Plugin gets disabled after some time

### ISSUE THREAD

**Issue by AWegner1** [DebugBill/glpi2mdt#12]
hi,
we established a new installation of glpi in our environment. 
After installation and configuration of your MDT-Plugin i noticed that the plugin disables itself after a few minutes, even after enabling it again manually.
Could you give me some point where I can start to investigate?
GLPI-Version: 9.3.0
Plugin-Version: 0.2.1

Thanks in advance,
Alex

**Comment by DebugBill** [comment]
Hi,

I never faced such a behaviour and I must confess I am not aware of a mecanism that disables a previously enabled plugin.
You say it is a new install. Was the plugin working fine in your previous installation?
For investigation I would search the PHP and SQL log files first as most of the time the answer is there. Maybe you'll find the reason why the plugin gets disabled.

I developped this plugin while working at my previous employer. I have since left and I am not maintening it anymore. I even don't use it anymore so I'm affraid I won't be able to debug it.

**Comment by AWegner1** [comment]
Hi,

thanks for your fast reply, I will inspect the logs and see what I could find.
It is a brand new installation, I did not use GLPI ever since now.

I will report back, when I find something.

**Comment by AWegner1** [comment]
Okay I'm back with some infos:
It happens every time cron runs the cron.php from GLPI and nothing has to be done.
I setup another installation on a different server and imported our database, and there it does not happen. Other plugins are not installed there.
Could it be an interference with a different plugin?
I try to investigate in this direction later on, the Logs do not really give a clue :(

**Comment by AWegner1** [comment]
Hi, 

i finally could figured the cause of the problem.
After investigating the source code, the 'inactivate'-function must have been called.
One thought later I remembered that our system runs different php-versions using php-fpm.
Running cron using /usr/bin/php runs the correct version, but uses a different php.ini - hence the unixODBC module is not loaded so php throws an error about it and glpi disables the plugin because the requirements aren't met anymore.
Thank you for your help, maybe I have some time to keep updating plugin when I have some time.

**Comment by DebugBill** [comment]
Hi,,

Good news you found the problem. Tricky one though :-)
