### ISSUE TITLE
Plugin not working on glpi 9.2 installed on Windows server

### ISSUE THREAD

**Issue by keepcool5283** [DebugBill/glpi2mdt#4]
Hello,

I have a problem to install the plugin on my Glpi 9.2.
I installed GLPI on w2012 server and when I had the plugin receive an error : "Configuration PHP incompatible. Un module PHP MSSQL ou ODBC est nécessaire" (sorry it's in French).

Do you know how can I fix it ?

Thanks

**Comment by keepcool5283** [comment]
Just a little up to know if you have an idea on this prob. Thanks

**Comment by DebugBill** [comment]
Hi, 
As the message clearly (I thought) says, you can fix it by installing one of the necessary PHP modules. Install either PHP MSSQL or PHP ODBC and your problem will be solved.

**Comment by JulienG78** [comment]
Same here, I'm on debian with php 5.6, odbc and mssql are installed and enabled, but I still have the error message on GLPI saying that ODBC must be installed.

Can you at list tell in the readme file which lib/modules we have to install ? i'm searching on internet since 1hr, I don't find anything else related to ODBC to install on debian.

**Comment by DebugBill** [comment]
The readme file already says:
_"Prerequisites
   (MSSQL or ODBC) and SimpleXML PHP modules must be installed"_

Are you sure those PHP modules are really installed and available to PHP? How did you make sure? Can you post some evidence, like for example a phpinfo() output?
Attached is an extract from mine where the ODBC module clearly appears
![phpinfo](https://user-images.githubusercontent.com/25805255/33558486-39335dd2-d90a-11e7-9e78-45e65b594772.png)
